package day.vitayuzu.neodb.data.schema

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

// --- 主目标 Data Class ---

/**
 * Present a Mastodon Status actually.
 * NeoDB related fields are in [ExtNeoDB].
 * Generated by LLM.
 */
@Serializable
data class PaginatedPostList(
    val data: List<PostSchema>,
    override val pages: Int,
    val count: Int,
) : HasPages

// --- Enums ---

@Serializable
enum class PostVisibility {
    @SerialName("public") PUBLIC,

    @SerialName("unlisted") UNLISTED,

    @SerialName("private") PRIVATE,

    @SerialName("direct") DIRECT,
}

@Serializable
enum class MediaAttachmentType {
    @SerialName("unknown") UNKNOWN,

    @SerialName("image") IMAGE,

    @SerialName("gifv") GIFV,

    @SerialName("video") VIDEO,

    @SerialName("audio") AUDIO,
}

// --- Dependent Schemas ---

@Serializable
data class CustomEmoji(
    val shortcode: String,
    val url: String,
    @SerialName("static_url") val staticUrl: String,
    @SerialName("visible_in_picker") val visibleInPicker: Boolean,
    val category: String,
)

@Serializable
data class AccountField(
    val name: String,
    val value: String,
    @SerialName("verified_at") val verifiedAt: String? = null, // anyOf with null
)

@Serializable
data class Account(
    val id: String,
    val username: String,
    val acct: String,
    val url: String,
    @SerialName("display_name") val displayName: String,
    val note: String,
    val avatar: String,
    @SerialName("avatar_static") val avatarStatic: String,
    val header: String,
    @SerialName("header_static") val headerStatic: String,
    val locked: Boolean,
    val fields: List<AccountField>,
    val emojis: List<CustomEmoji>,
    val bot: Boolean,
    val group: Boolean,
    val discoverable: Boolean,
    val indexable: Boolean,
    // moved: anyOf [boolean, Account, null]. JsonElement? 是最安全的表示方式。
    // 后续在使用时需要判断其具体类型 (JsonPrimitive, JsonObject, JsonNull)
    val moved: JsonElement? = null,
    @SerialName("suspended") val suspended: Boolean = false, // Has default in schema, but also in required list
    @SerialName("limited") val limited: Boolean = false, // Has default in schema, but also in required list
    @SerialName("created_at") val createdAt: String,
)

@Serializable
data class MediaAttachment(
    val id: String,
    val type: MediaAttachmentType,
    val url: String,
    @SerialName("preview_url") val previewUrl: String,
    @SerialName("remote_url") val remoteUrl: String? = null, // anyOf with null
    // meta: object with additionalProperties: true. JsonElement (JsonObject) is suitable.
    val meta: JsonElement, // 通常会是一个 JsonObject
    val description: String? = null, // anyOf with null
    val blurhash: String? = null, // anyOf with null
)

@Serializable
data class StatusMention(
    val id: String,
    val username: String,
    val url: String,
    val acct: String,
)

@Serializable
data class StatusTag(
    val name: String,
    val url: String,
)

@Serializable
data class PostSchema(
    val id: String,
    val uri: String,
    @SerialName("created_at") val createdAt: String,
    val account: Account,
    val content: String,
    val visibility: PostVisibility,
    val sensitive: Boolean,
    @SerialName("spoiler_text") val spoilerText: String,
    @SerialName("media_attachments") val mediaAttachments: List<MediaAttachment>,
    val mentions: List<StatusMention>,
    val tags: List<StatusTag>,
    val emojis: List<CustomEmoji>,
    @SerialName("reblogs_count") val reblogsCount: Int,
    @SerialName("favourites_count") val favouritesCount: Int,
    @SerialName("replies_count") val repliesCount: Int,
    val url: String? = null, // anyOf with null
    @SerialName("in_reply_to_id") val inReplyToId: String? = null, // anyOf with null
    @SerialName("in_reply_to_account_id") val inReplyToAccountId: String? = null, // anyOf with null
    val language: String? = null, // anyOf with null
    val text: String? = null, // anyOf with null
    @SerialName("edited_at") val editedAt: String? = null, // anyOf with null
    val favourited: Boolean = false, // Has default, but also in required.
    val reblogged: Boolean = false, // Has default, but also in required.
    val muted: Boolean = false, // Has default, but also in required.
    val bookmarked: Boolean = false, // Has default, but also in required.
    val pinned: Boolean = false, // Has default, but also in required.
    @SerialName("ext_neodb") val extNeoDB: ExtNeoDB,
)
