name: Validate fastlane metadata

on: [ pull_request ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
