name: Validate fastlane metadata

on:
  pull_request:
  push:
    branches: [ "main" ]
    paths: [ "fastlane/**" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
