name: Validate fastlane metadata

on: [ pull_request ]
jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
      with:
        usePlayStoreLocales: true # optional
