name: Nightly build

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "docs/**", "fastlane/**", "**.md" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build release
        env:
          SIGN_KEY_BASE64: ${{ secrets.SIGN_KEY_BASE64 }}
          SIGN_KEY_PWD: ${{ secrets.SIGN_KEY_PWD }}
          SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
        run: ./gradlew assembleRelease

      - name: Rename APK
        run: |
          set -e
          SHA=${{ github.sha }}
          echo "Release version is: $SHA"
          
          APK_DIR="app/build/outputs/apk/release"
          mv ${APK_DIR}/app-release.apk NeoDB-You-nightly-${SHA}.apk
          echo "APK renamed to NeoDB-You-nightly-${SHA}.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nightly
          path: NeoDB-You-nightly-${{ github.sha }}.apk
