name: Release

on:
  push:
    tags:
      - v*
      
jobs:   
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build release
        env:
          SIGN_KEY_BASE64: ${{ secrets.SIGN_KEY_BASE64 }}
          SIGN_KEY_PWD: ${{ secrets.SIGN_KEY_PWD }}
          SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
        run: ./gradlew assembleRelease

      - name: Rename APK
        run: |
          set -e
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          echo "Release version is: $VERSION"
          
          APK_DIR="app/build/outputs/apk/release"
          mv ${APK_DIR}/app-arm64-v8a-release.apk NeoDBYou-arm64-v8a-${{ GITHUB_REF_NAME }}.apk
          mv ${APK_DIR}/app-armeabi-v7a-release.apk NeoDBYou-armeabi-v7a-${{ GITHUB_REF_NAME }}.apk
          mv ${APK_DIR}/app-x86-release.apk NeoDBYou-x86-${{ GITHUB_REF_NAME }}.apk
          mv ${APK_DIR}/app-x86_64-release.apk NeoDBYou-x86_64-{{ GITHUB_REF_NAME }}.apk
          mv ${APK_DIR}/app-universal-release.apk NeoDBYou-universal-{{ GITHUB_REF_NAME }}.apk
          
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.apk"
